from __future__ import annotations

from typing import Literal, TypedDict

FigureForm = Literal[
    "aquatic-fish", "aquatic-mammal", "aquatic-reptile", "bat", "bear", "bird", "brute", "centipede", "crab", "frog",
    "gargoyle", "hippogriff", "hoofed", "humanoid", "insect", "plant", "primate", "pterosaur", "quadruped",
    "reptile", "scorpion", "snake", "spider", "swarm", "theropod", "weapon", "winged-insect",
]


class FigureProfile(TypedDict):
    form: FigureForm
    detail: str


def _p(form: FigureForm, detail: str) -> FigureProfile:
    return {"form": form, "detail": detail}


MONSTER_FIGURE_PROFILES: dict[str, FigureProfile] = {
    "Allosaurus": _p("theropod", "allosaurus"),
    "Animated Armor": _p("humanoid", "animated-armor"),
    "Animated Flying Sword": _p("weapon", "flying-sword"),
    "Ankylosaurus": _p("reptile", "ankylosaurus"),
    "Archelon": _p("aquatic-reptile", "archelon"),
    "Awakened Shrub": _p("plant", "shrub"),
    "Awakened Tree": _p("plant", "tree"),
    "Axe Beak": _p("bird", "beak"),
    "Baboon": _p("primate", "baboon"),
    "Badger": _p("quadruped", "badger"),
    "Bandit": _p("humanoid", "bandit"),
    "Bandit Captain": _p("humanoid", "bandit-captain"),
    "Bat": _p("bat", "bat"),
    "Black Bear": _p("bear", "bear"),
    "Blood Hawk": _p("bird", "blood-hawk"),
    "Boar": _p("quadruped", "tusks"),
    "Brown Bear": _p("bear", "bear"),
    "Camel": _p("hoofed", "camel"),
    "Cat": _p("quadruped", "cat"),
    "Commoner": _p("humanoid", "commoner"),
    "Constrictor Snake": _p("snake", "snake"),
    "Crab": _p("crab", "crab"),
    "Crocodile": _p("reptile", "crocodile"),
    "Cultist": _p("humanoid", "cultist"),
    "Deer": _p("hoofed", "antlers"),
    "Dire Wolf": _p("quadruped", "canine"),
    "Draft Horse": _p("hoofed", "equine"),
    "Eagle": _p("bird", "raptor"),
    "Elk": _p("hoofed", "antlers"),
    "Flying Snake": _p("snake", "flying-snake"),
    "Frog": _p("frog", "frog"),
    "Gargoyle": _p("gargoyle", "gargoyle"),
    "Giant Badger": _p("quadruped", "badger"),
    "Giant Bat": _p("bat", "bat"),
    "Giant Boar": _p("quadruped", "tusks"),
    "Giant Centipede": _p("centipede", "centipede"),
    "Giant Constrictor Snake": _p("snake", "snake"),
    "Giant Crab": _p("crab", "crab"),
    "Giant Crocodile": _p("reptile", "crocodile"),
    "Giant Eagle": _p("bird", "raptor"),
    "Giant Elk": _p("hoofed", "antlers"),
    "Giant Fire Beetle": _p("insect", "beetle"),
    "Giant Goat": _p("hoofed", "horns"),
    "Giant Lizard": _p("reptile", "lizard"),
    "Giant Owl": _p("bird", "owl"),
    "Giant Rat": _p("quadruped", "rodent"),
    "Giant Scorpion": _p("scorpion", "giant-scorpion"),
    "Giant Venomous Snake": _p("snake", "snake"),
    "Giant Vulture": _p("bird", "vulture"),
    "Giant Wasp": _p("winged-insect", "wasp"),
    "Giant Weasel": _p("quadruped", "mustelid"),
    "Giant Wolf Spider": _p("spider", "spider"),
    "Goat": _p("hoofed", "goat"),
    "Goblin Boss": _p("humanoid", "goblin-boss"),
    "Goblin Minion": _p("humanoid", "goblin"),
    "Goblin Warrior": _p("humanoid", "goblin"),
    "Grick": _p("snake", "grick"),
    "Griffon": _p("hippogriff", "griffon"),
    "Grimlock": _p("humanoid", "grimlock"),
    "Guard": _p("humanoid", "guard"),
    "Guard Captain": _p("humanoid", "guard-captain"),
    "Hawk": _p("bird", "raptor"),
    "Hippogriff": _p("hippogriff", "hippogriff"),
    "Hippopotamus": _p("quadruped", "hippopotamus"),
    "Hobgoblin Warrior": _p("humanoid", "hobgoblin"),
    "Hyena": _p("quadruped", "hyena"),
    "Jackal": _p("quadruped", "canine"),
    "Killer Whale": _p("aquatic-mammal", "orca"),
    "Knight": _p("humanoid", "knight"),
    "Kobold Warrior": _p("humanoid", "kobold"),
    "Lemure": _p("brute", "lemure"),
    "Lizard": _p("reptile", "lizard"),
    "Manticore": _p("quadruped", "manticore"),
    "Mastiff": _p("quadruped", "canine"),
    "Merfolk Skirmisher": _p("humanoid", "merfolk-skirmisher"),
    "Minotaur Skeleton": _p("brute", "minotaur-skeleton"),
    "Mule": _p("hoofed", "equine"),
    "Noble": _p("humanoid", "noble"),
    "Ogre": _p("brute", "ogre"),
    "Ogre Zombie": _p("brute", "ogre-zombie"),
    "Owl": _p("bird", "owl"),
    "Owlbear": _p("bear", "owlbear"),
    "Panther": _p("quadruped", "cat"),
    "Pegasus": _p("hoofed", "pegasus"),
    "Plesiosaurus": _p("aquatic-reptile", "plesiosaur"),
    "Polar Bear": _p("bear", "bear"),
    "Pony": _p("hoofed", "equine"),
    "Pteranodon": _p("pterosaur", "pteranodon"),
    "Rat": _p("quadruped", "rodent"),
    "Raven": _p("bird", "corvid"),
    "Reef Shark": _p("aquatic-fish", "shark"),
    "Rhinoceros": _p("hoofed", "horn"),
    "Riding Horse": _p("hoofed", "equine"),
    "Saber-Toothed Tiger": _p("quadruped", "sabertooth"),
    "Scorpion": _p("scorpion", "scorpion"),
    "Scout": _p("humanoid", "scout"),
    "Skeleton": _p("humanoid", "skeleton"),
    "Spider": _p("spider", "spider"),
    "Swarm of Bats": _p("swarm", "bats"),
    "Swarm of Crawling Claws": _p("swarm", "crawling-claws"),
    "Swarm of Insects": _p("swarm", "insects"),
    "Swarm of Rats": _p("swarm", "rats"),
    "Swarm of Venomous Snakes": _p("swarm", "venomous-snakes"),
    "Tiger": _p("quadruped", "cat"),
    "Tough": _p("humanoid", "tough"),
    "Triceratops": _p("reptile", "triceratops"),
    "Tyrannosaurus Rex": _p("theropod", "tyrannosaurus"),
    "Venomous Snake": _p("snake", "snake"),
    "Violet Fungus": _p("plant", "violet-fungus"),
    "Vulture": _p("bird", "vulture"),
    "Warhorse": _p("hoofed", "equine"),
    "Warhorse Skeleton": _p("hoofed", "skeleton-equine"),
    "Warrior Infantry": _p("humanoid", "infantry"),
    "Warrior Veteran": _p("humanoid", "veteran"),
    "Weasel": _p("quadruped", "mustelid"),
    "Wolf": _p("quadruped", "canine"),
    "Worg": _p("quadruped", "canine"),
    "Wyvern": _p("reptile", "wyvern"),
    "Zombie": _p("humanoid", "zombie"),
}
